[project]
name = "primitive-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Бойко Галя", email = "neverever3349@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
project = "primitive_db.main:main"

[build-system]
requires = ["uv_build>=0.11.17,<0.12.0"]
build-backend = "uv_build"
